apiVersion: v1
kind: Service
metadata:
  namespace: {{ namespace }}
  name: kibana-oauth2-proxy
  labels:
    app: kibana-oauth2-proxy
spec:
  selector:
    app: kibana-oauth2-proxy
  type: NodePort
  ports:
    - port: 4180
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ namespace }}
  name: kibana-oauth2-proxy
  labels:
    app: kibana-oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-oauth2-proxy
  template:
    metadata:
      labels:
        app: kibana-oauth2-proxy
    spec:
      containers:
        - name: kibana-oauth2-proxy
          image: machinedata/oauth2_proxy
          ports:
            - name: http
              containerPort: 4180
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
          env:
            - name: OAUTH2_PROXY_PROVIDER
              value: github
            - name: OAUTH2_PROXY_GITHUB_ORG
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: github.org
            - name: OAUTH2_PROXY_GITHUB_TEAM
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: github.team
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: client.id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: client.secret
            - name: OAUTH2_PROXY_COOKIE_NAME
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: cookie.name
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-secrets
                  key: cookie.secret
            - name: OAUTH2_PROXY_UPSTREAM
              value: "http://kibana.{{ namespace }}.svc.cluster.local:5601"
